### ISSUE TITLE
Reconnect machine when plugged in

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1020] opened 2018-10-19 22:22 UTC
## Summary

Is there some way to get Plover to reconnect to the StenoMod (or another writer like the Stentura 400 SRT) when I plug it in? 

## Reproducing

Open Plover. Connect StenoMod to your computer. (probably is reproducible with other steno writers as well) Notice how Plover doesn't work until you click the "reconnect machine" button. Wondering if there's a way for Plover to auto-reconnect by somehow detecting that the machine was plugged in.

## Plover Version

Plover 4.0.0.dev8+8.ge062cda 

## System

macOS 10.13.6 High Sierra

**Comment by morinted** [comment] 2018-10-26 18:00
Yep, this is a super important feature that we definitely want to have. Thanks for the request, I'll count it as a duplicate of the open issue #596

**Closed by morinted** 2018-10-26 18:00 UTC
