### ISSUE TITLE
Issues with symbols `{` on linux Ubuntu.

### ISSUE THREAD

**Issue by cmester0** [openstenoproject/plover#1503] opened 2022-03-16 13:17 UTC
When inputting `TPR-BGT` i get `7` instead of `{` that is `\{{^}` gives an incorrect output. Similar issues happen with other symbols. 

 - OS: Ubuntu 21.10
 - Plover Version 4.0.0

**Comment by cmester0** [comment] 2022-03-16 16:42
Resolved by running:
`./plover.AppImage -s plover_plugins install -v 'PyQt5==5.14.2' 'PyQt5-sip==12.7.2'`

**Comment by benoit-pierre** [comment] 2022-03-16 16:47
Please provide more information: what version of Plover are you using exactly? Does the incorrect output happen in all applications? I don't see how (possibly) downgrading PyQt5 is relevant, unless maybe if the issue happens only withing the Plover GUI text fields.

**Comment by benoit-pierre** [comment] 2022-03-16 17:13
What layout do you use? Do you use ibus? xmodmap? How are `7` and `{` mapped on your keyboard layout?

**Comment by cmester0** [comment] 2022-05-25 22:01
Seems to be an issue with a missing modifier key, tried printing the mapping and got:
```
keysym_to_string 55
is_latin1 55
chr 7
16:0=37[7]
keysym_to_string 47
is_latin1 47
chr /
16:1=2f[/]
keysym_to_string 123
is_latin1 123
chr {
16:80=7b[{]
```
So when you send 123 it should add the 80 modifier?

**Comment by cmester0** [comment] 2022-05-25 22:20
The issue seems to be that my default layout is danish, which it knows is the `AltGr + 8` key combination on the keyboard, however when I have english keyboard active this no longer works. So it only works when I use the default keyboard layout.

**Comment by cmester0** [comment] 2022-06-02 09:25
@benoit-pierre hope this helps.

**Comment by benoit-pierre** [comment] 2022-06-02 10:44
Looks like a duplicate of #650.

For Wayland, assuming you're using a compatible config, you can check [this branch](https://github.com/openstenoproject/plover/compare/master...benoit-pierre:wayland-sway) (see [discussion](#1461)).

**Closed** 2022-06-03 10:58 UTC
Labels: bug, linux
