### ISSUE TITLE
Carriage return is not properly undone on Windows.

### ISSUE THREAD

**Issue by Mqrius** [openstenoproject/plover#166] opened 2013-12-25 13:37 UTC
When stroking a carriage return with R-R, and then an undo with *
the previous word is deleted including the carriage return, while one would expect only the carriage return to be deleted.

Tested with Windows 7, Plover 2.5.7

**Comment by morinted** [comment] 2015-09-27 20:51
Let's call this a duplicate of #159 (which has been renamed). Closing for discussion there.

**Closed by morinted** 2015-09-27 20:51 UTC
