### ISSUE TITLE
Quirk in paper tape display 

### ISSUE THREAD

**Issue by mike-ady** [openstenoproject/plover#825] opened 2017-10-28 21:38 UTC
Classification: Possible Bug

Reproducibility: Always

## Summary

I am working on Windows 8.1 with the Stenoboard firmware in NKRO mode.  When I type "#T-#P", the Plover paper tape display shows #TP, but all 3 characters are on separate lines.   The firmware is sending "17wi".  Plover generates the chord: " # it."  Is that correct?   (I am using the default dictionaries.)

![single_chord_on_3_lines](https://user-images.githubusercontent.com/33185827/32138559-c2ccf8d6-bbf1-11e7-9db9-4335b4c9109f.png)

Note that if I stroke "#T-P" (with just one numeric key in any combination) then the paper tape display shows #TP on a single line, and I obtain the translation "17" as expected.

Note also that the Stenoboard firmware runs on the Arduino platform.  The Arduino USB keyboard interface is only 6KRO.  The firmware apparently uses the following scheme to achieve NKRO:

First it sends a "press" for the first character, then a "press" followed by a "release" for all remaining characters, and finally it sends a "release all".

## Steps to Reproduce

1. I send "17wi" to Plover in NKRO mode.

## Expected Results

1. Plover should at least display the chord on a single line.
2. Perhaps Plover should translate the chord as a number.

## Actual Results

1. Plover displays the chord on 3 lines on its paper tape display, and it emits an unexpected translation.

## Version

Plover version: 4.0.0.dev1+20.g60a373f.

Installed via: download from openstenoproject.org

## Notes

Work around:  I have modified the firmware to only send out the first numeric character when there are multiple numeric characters in a chord.  I'm not sure if that is the right thing to do.

## Configuration

OS:  Windows 8.1 64-bit

**Comment by benoit-pierre** [comment] 2017-10-28 21:43
I think this was fixed in master. Please see if you can reproduce the issue with this [version](https://ci.appveyor.com/api/buildjobs/0q7i19r3k62cjs5a/artifacts/dist%2Fplover-4.0.0.dev3%2B31.g29d3dfe-win32.setup.exe).

**Comment by mike-ady** [comment] 2017-10-28 22:08
Thanks Benoit,

I uninstalled the version that I referenced in my previous post.  After 
installing the version in your link, nothing happens when I attempt to 
run Plover.

I noticed that the download was much smaller than my previous version: 
6.4 MB, instead of 21.2 MB.  The Plover executable also appears to be 
much smaller.  Is there perhaps a problem with the build?

**Comment by benoit-pierre** [comment] 2017-10-28 22:18
Indeed... Looks like something has been wrong with the Windows artifacts for some time... *sigh*
I'll look into it, in the mean time, try this version instead: https://ci.appveyor.com/project/morinted/plover/build/427-walbtleo/artifacts

**Comment by mike-ady** [comment] 2017-10-28 22:32
Thanks Benoit,

That version seems to work correctly.

**Comment by benoit-pierre** [comment] 2017-10-28 22:33
OK, thanks for confirming.

**Closed by benoit-pierre** 2017-10-28 22:33 UTC
