### ISSUE TITLE
( ͡° ͜ʖ ͡°) sometimes written as ( °  °)

### ISSUE THREAD

**Issue by sp3ctum** [openstenoproject/plover#967] opened 2018-06-05 19:10 UTC
## Summary

I have a stroke for the so-called Lenny face, `( ͡° ͜ʖ ͡°)` defined as the stroke L-N or HR-PB. In some sessions, when I write that stroke, this face is printed out: `( °  °)`. The characters in the middle have been converted to space characters (I inspected them in Emacs to find this out).

## Reproducing

Here is a stroke log of the stroke that fails:
```
2018-06-05 22:02:12,415 Stroke(HR-PB : ['H-', 'R-', '-P', '-B'])
2018-06-05 22:02:12,426 Translation(('HR-PB',) : "( ͡° ͜ʖ ͡°)")
```
It's unclear to me how exactly to reproduce this. I open Plover one day, then do my work and possibly put the computer to sleep for the night. At some point I find that the ( ͡° ͜ʖ ͡°) face is broken.

I can always fix the stroke by restarting Plover.

## Plover Version

I'm running Plover from source, today I was testing https://github.com/openstenoproject/plover/pull/964
The sha is 2fbd465 .

## System

Fedora Linux 24
Linux QFINL014 4.11.12-100.fc24.x86_64 #1 SMP Fri Jul 21 17:35:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I know this isn't much to go by, but if you have any ideas on what I should inspect or capture or tinker, I should be able to make time during my day.

**Comment by benoit-pierre** [comment] 2018-06-05 19:27
Plover will dynamically patch the keyboard layout to add missing characters needed for output. So if another program does patch the layout (or its reset by the Xorg server) that could explain the issue (and why restarting fix it).

**Comment by sp3ctum** [comment] 2018-06-06 06:30
Yes, that seems to be related. I am able to reproduce this now:

- start Plover, verify that the stroke works
- issue the command `setxkb se` to change the keyboard layout to Swedish
- now the stroke is broken
- changing back to Finnish with `setxkbmap fi` does not fix the issue

Do you think that the patching could be done more often? Or maybe even manually?

**Comment by DanLanglois** [comment] 2018-06-06 07:16
Right now, in your dictionary, you have maybe this:

"HR-PB": "(° ʖ °)",

It might be worth trying a subtle change, like this:

"HR-PB": "(° {^}{} ʖ °)",

As an explanation, I'm thinking that Plover aside, sometimes the character I've just pressed isn't in the font I'm using (especially likely if it's a weird symbol). Often the program I'm using will then switch font to one that does have the symbol, and then leave me in that font.  This is a bit strange, since it affects the subsequent characters I  type. 

And anyways, I have found, that a good workaround for occasional symbols with this problem is to type space, then move left, then type the symbol you want, then move right again.

**Comment by sp3ctum** [comment] 2018-06-07 06:17
I just got this error with the ``` ` ``` character too. That is strange, because that is a stroke that is built in to the Plover theory.
It's not a huge issue though, I seem to be able to fix it by restarting Plover.

**Comment by DanLanglois** [comment] 2018-06-16 21:28
'That is a stroke that is built in to the Plover theory.'

Just to touch base, here, that I am at a loss as to how to interpret this. Do I need to know what you mean by 'the Plover theory'? Do I need to know what is a stroke? Rest assured that I've been using Plover for years, but also, that I've never seen any issue such as you describe (not that you actually describe it, I'm just saying). 

'I just got this error'

Note, that this is unclear. Something didn't display as you expected? What did you expect, and what happened? 

Meanwhile, did you see my previous suggestion? I mean, tell me it didn't work, fine. Did you see it?

**Comment by sp3ctum** [comment] 2018-06-17 16:38
You're right! Unfortunately I forgot what happened to be honest. I will try out a few things the next time I notice this. Mostly I wanted to create an issue just so that this isn't totally forgotten.

What I meant was this stroke: 
```
`:
   KH-FG
```

I am pretty sure that it wrote nothing when I tried it in this broken mode.

I saw your suggestion too. I can try that out then too.

**Comment by sp3ctum** [comment] 2018-06-18 06:07
Hey, I just got the error again. I was able to try out your workaround, but unfortunately it made no change to the behavior I already saw.

For completeness, here is the stroke I used:

```
({^}{} ͡° ͜ʖ ͡°)
```

**Comment by benoit-pierre** [comment] 2022-06-02 10:54
Duplicate of #650.

**Closed by benoit-pierre** 2022-06-02 10:54 UTC
Labels: bug, linux
