### ISSUE TITLE
Apple cannot verify developer

### ISSUE THREAD

**Issue by Wizz4ve** [openstenoproject/plover#1493] opened 2022-02-27 22:34 UTC
**Describe your issue**

A clear and concise description of what you're trying to do. E.g. "I'm trying to connect my Stentura 400SRT to Plover over USB but there's no output."

**Steps you've taken**

What have you tried to do to get this to work?

4. Bad behavior happens

**Expected behavior**

**Screenshots**

**Operating system**

 - OS: [e.g. Windows 10, Ubuntu 20.04, macOS Catalina]
 - Plover Version [e.g. 3.x, 4.x, weekly]

**Hardware**

If applicable, let us know what machine you're experiencing the issue with and how it's connected to Plover, as well as a screenshot of the machine configuration inside Plover.

**Comment by Wizz4ve** [comment] 2022-02-27 22:37
Downloaded Plover app
Moved to Applications folder
Cannot open app: Error message 
-“Plover” cannot be opened because the developer cannot be verified.
-macOS cannot verify that this app is free from malware
-objects.githubusercontent.com
-Only options: Cancel or Move to Trash

**Comment by benoit-pierre** [comment] 2022-02-27 22:39
Duplicate of #910.

Check the [install instructions](https://github.com/openstenoproject/plover/wiki/Installation-Guide#install-plover-on-mac) for a workaround.

**Comment by Wizz4ve** [comment] 2022-02-27 22:40
-MacBook Air Retina 13 inch 2019
-Software: macOS Monterey 12.0.1

**Closed by benoit-pierre** 2022-02-27 22:39 UTC
Labels: support
