### ISSUE TITLE
Configuration changes only save when exiting Plover

### ISSUE THREAD

**Issue by nsmarkop** [openstenoproject/plover#938] opened 2018-04-16 04:16 UTC
## Summary

The plover.cfg file for storing Plover's configuration on seems to be updated when exiting Plover. If you make large configuration changes like remapping keys and then Plover crashes or otherwise closes unexpectedly before you have restarted then that configuration will be lost.

Ideally the configuration file would be updated upon applying the changes.

## Reproducing

1. Start Plover
2. Open Configure
3. Make changes that would affect plover.cfg - for example, changing the MIDI port, changing the system, changing key mappings for a machine, etc.
4. Click Apply then OK
5. Confirm that the configuration changes are affecting the current instance of Plover
6. Open plover.cfg and confirm the configuration file has not been updated
7. To go the extra mile, get Plover to crash or close unexpectedly and upon opening it again see that the old configuration is what is loaded

## Plover Version

Plover v4.0.0.dev8+8.ge062cda6 (latest weekly)

## System

Windows 10

**Comment by benoit-pierre** [comment] 2018-04-16 07:00
Duplicate of #915.

**Closed by benoit-pierre** 2018-04-16 07:00 UTC
