### ISSUE TITLE
Plugin manager stopped fetching updates

### ISSUE THREAD

**Issue by SeaLiteral** [openstenoproject/plover#1178] opened 2020-12-18 20:15 UTC
## Summary
For the last couple of days, trying to use the plugin manager has only been able to show plugins that are already installed, it isn't able to fetch plugins, updates or metadata. It shows an error message too.

## Reproducing

Start Plover and open the plugins manager. Then you can see which plugins are already installed, but you can't see other plugins or install or update anything. And you get an error message saying `PyPI's XMLRPC API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information."`

It's been like this for three days or so so far.

## Plover Version

Plover 4.0.0.dev8+66.g685bd33  (AppImage)

## System

Ubuntu 20.04.1LTS, running the AppImage

**Comment by benoit-pierre** [comment] 2020-12-18 20:21
Duplicate of https://github.com/benoit-pierre/plover_plugins_manager/issues/14.

**Closed** 2020-12-18 20:22 UTC
