### ISSUE TITLE
RTF dictionary bug with undoable new lines and returns?

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#1128] opened 2020-05-24 22:28 UTC
## Summary

I just found out about undoable line breaks (\n, \r, \t, etc.). Up to now I have just been grumbling if I had to undo more than a whole line of steno.  So I was all excited and all set to replace all my {#Return}s in my RTF dictionaries with {\r}s.

So I started with one just make sure I knew what I was doing.  Apparently I don't.   I used Plover to define the stroke SPH-PBG/SPH-PBG (something something) as {\r}.  I then stroked something something in Word, but nothing happened. (I mean, what actually happened was the word "something" appeared and then disappeared as I stroked, but no _new line_ happened.)

So I tried using Plover to define the SPH-PBG/SPH-PBG stroke as just \r, then tried that in Word. And it worked.  If I went to my NEW ENTRIES dictionary in Plover, I saw that SPH-PBG/SPH-PBG was defined as \r.  And as I stenoed into Word, it did in fact add a new line.  

HOWEVER.  I looked at the entry in my RTF dictionary and it looked like this:

{\*\cxs SPH-PBG/SPH-PBG}

Nothing to the right of it.  I wasn't very clear how this empty entry was creating a new line in Word. Then I figured Plover must create a single working dictionary to refer to, as well as update all the loaded dictionaries when a change is made.  Or something like that, makes sense.

So I closed Plover and reopened it.  The RTF entry was still the same, and now Plover did nothing when I stroked it into Word.  And Plover showed the entry as defined as (empty field).

Long story short, I tried manually editing the RTF dictionary with the sorts of things I'm used to seeing in my RTF dictionaries (like putting a \ in front of the \r, putting {} around the entry, using \n instead of \r, etc. etc.), but nothing seemed to work.  In fact defining it in Plover as described in the dictionary explanation online as {\r} made the RTF entry this:

{\*\cxs SPH-PBG/SPH-PBG}{
}

(Note the literal new line.  :-)}

So, 1) This is apparently a bug with RTF dictionaries.

And 2), any ideas on what the syntax should be in an RTF to make it work?  I assumed it would come out in RTF as \{\\r\} or something instead of just coming out blank?

Thanks for your input!  I'm happy to clarify if I wasn't clear!  Love Plover!

## Plover Version

Possibly relevant information:
Plover 4.0.0.dev8+8.ge062cda
Windows 10
Stentura Protégé
Phoenix Theory
RTF dictionaries, not JSON

**Comment by JoshuaGrams** [comment] 2020-05-24 23:01
I'm not sure this syntax is even supposed to work in RTF dictionaries, except by accident. The RTF/CRE loader is definitely an importer/converter: looks like it changes `\r` and `\n` to `{#return}`.

Is there a reason you can't use a separate JSON dictionary for these entries?

**Comment by ms009986** [comment] 2020-05-25 01:33
Sure, I can do that if there's no workaround...but isn't Plover supposed to support RTF dictionaries?

**Comment by gdwaynewarner** [comment] 2020-05-25 09:04
I actually reported a problem which pointed out that RTF dictionaries with definitions that look like this --
{^}ing{^}
 -- started looking like this:
{^ ing ^}
... which, as you might imagine, completely messes up what that outline was supposed to do.
I reported that both [here](https://groups.google.com/forum/#!topic/ploversteno/qo_vXTcJLxY) and [here](https://github.com/openstenoproject/plover/issues/773).
So, the work-around for outlines like that is to create a .json dictionary for them.

**Comment by ms009986** [comment] 2020-05-25 18:55
Hi Glen!  I understand what you mean; I've   never been able to make a period and a closing quote work. RTF just did not like the whole idea at all and kept sticking in a space before the period, no matter how many ^s I jammed in there. But last night after a lot of trial and error the JSON dictionary was much more tolerant, and I was able to finally make that work after years of extra spaces. So I've always been resistant to JSON since RTF is so universal, but maybe using a JSON dictionary will be a way to solve all the minor but nagging things I haven’t been able to make work before.

Part of the problem is I don’t know what Plover syntax is supposed to be. My main dictionaries originally came from Eclipse and I'm afraid they're highly biased towards the way Eclipse thinks things ought to be. In Eclipse the syntax would be {."}, but I don’t know whether Plover agrees with Eclipse about that or has its own ideas about how to do things. Certainly in an RTF dictionary that syntax doesn't work.

The answers may all be in the main.JSON dictionary that comes with Plover, but not being a Sten-Ed person I usually am clueless as to what to look for.

But anyway, if the Plover people tell me I need a JSON dictionary, then a JSON dictionary it shall be!

**Comment by JoshuaGrams** [comment] 2020-05-25 21:44
Yeah...the problem is that the stuff in the [Dictionary Format page](https://github.com/openstenoproject/plover/wiki/Dictionary-Format) is for Plover's JSON dictionaries. The RTF/CRE dictionaries have different ways to some of those things, while others might not even exist. For instance, RTF dictionaries use `\cxds` (delete space) instead of `{^}`.

Plover supports RTF dictionaries by attempting to convert them into Plover's internal format when loading, and converting back when saving. But I don't think it is a part of the code that has gotten a lot of attention, and I *think* some of the plover dictionary format codes may have been added without updating the RTF importer/exporter. I know that learning Phoenix has turned up a few places where Plover doesn't import RTF properly.

So...I could dig around in the source code to try and figure out if there's some sort of way to work around it, but if you can live with a JSON dictionary (at least for these definitions), they will just work...

**Comment by ms009986** [comment] 2020-05-26 03:18
I can live with it, that’s no problem. It was just that I am used to adding an entry and having Plover translate the entry into the RTF version of that entry (and we are talking years), and this is the first time something didn’t translate. I mean, some things were finicky here and there but they mostly worked.  So I thought you guys would just like another bug to track down.

No, this is actually a good thing. If JSON dictionaries are more functional than RTFs, then I am curious to find out what else they can do! Thanks for your help.  😀

**Comment by rbrewer123** [comment] 2020-06-09 19:46
See #159, which I opened over 6 years ago. I'm not quite sure if it's the same thing you're seeing or something different.  Despite the title, it is about a bug in RTF/CRE supprt. See my last comment in that bug.

My opinion is that any problems with RTF/CRE support in Plover should be filed as bugs because it means Plover cannot interoperate properly with the RTF/CRE standard.

**Comment by benoit-pierre** [comment] 2021-10-09 23:40
Should be fixed in #1364.

**Closed by benoit-pierre** 2021-10-09 23:40 UTC
