### ISSUE TITLE
Adding Translation with Space Placement: After option adds extra backslash/space on text input 

### ISSUE THREAD

**Issue by brownbaer** [openstenoproject/plover#1576] opened 2022-11-29 10:37 UTC
When trying to use the {PLOVER:ADD_TRANSLATION} feature, if you have the Space Placement set to "After Output" it will always add an extra / to the stroke, and an extra space on the translation you wrote. 

Not a huge bug, but annoying none the less.

BEFORE OUTPUT:
![image](https://user-images.githubusercontent.com/38145716/204507302-c1ed4ef9-8a9b-4586-bfc9-d0ef1e28793e.png)

AFTER OUTPUT:
![image](https://user-images.githubusercontent.com/38145716/204507158-9425de55-2e8c-4f42-9db8-9ce03f6b15a6.png)

**Comment by user202729** [comment] 2022-11-29 13:22
Duplicate of #1554

**Closed** 2022-11-29 13:22 UTC
Labels: bug
