### ISSUE TITLE
Undo stroke (*) does not behave correctly when undoing a new line stroke (R-R)

### ISSUE THREAD

**Issue by jaskoo80** [openstenoproject/plover#486] opened 2016-04-28 01:21 UTC
Classification: Bug

Reproducibility: Always
## Summary

The undo stroke (*) does not undo correctly when you try to undo a new line (R-R). 
It ends up deleting the new line as well as a portion of the previous word. 
There are generally two kinds of behaviours noticed.

**Behaviour A: If the previous line has only 1 word.**
It deletes the new line as well as the entire word except for the first letter.

**Behaviour B: If the previous line has more than 1 word.**
It deletes the new line as well as the last word of the previous line and leaves an additional space at the end of the line.

## Steps to Reproduce

**Behaviour A:**
1. Stroke HRAOEUPB
2. Stroke R-R
3. Stroke *
4. Stroke TPH*EBGS

**Behaviour B:**
1. Stroke HRAOEUPB
2. Stroke WORD
3. Stroke R-R
4. Stroke *
5. Stroke TPH*EBGS

## Expected Results

**Behaviour A:**
Line next

**Behaviour B:**
Line word next

## Actual Results

**Behaviour A:**
LNext

**Behaviour B:**
Line  next 
*(note the extra space)*

## Version

weekly-v2.5.8+576.ga90528e

## Notes
This is all on the default main.json dictionary.

**Comment by benoit-pierre** [comment] 2016-04-28 01:24
This is a duplicate of #159.

**Closed** 2016-04-28 01:57 UTC
Labels: duplicate

**Comment by morinted** [comment] 2016-04-28 02:16
As a workaround, Mirabai suggests using `{#BackSpace}` to undo return-strokes. That won't ruin your buffer.
