### ISSUE TITLE
Dictionaries in the cloud

### ISSUE THREAD

**Issue by marnanel** [openstenoproject/plover#716] opened 2017-03-07 13:16 UTC
Classification: Enhancement

Reproducibility: n/a

## Summary

We should have a built-in ability to read and write cloud dictionaries-- in particular, Google Drive, Dropbox, and WebDAV.

(In this case, the present local dictionaries will effectively become cached copies.)

**Comment by infodungeon** [comment] 2018-02-11 02:00
Providing a path setting to the dictionaries would allow this as Drive, Dropbos etc sync local drive stores.

**Comment by morinted** [comment] 2018-03-02 21:28
This is a duplicate of #128 and for now my stance is still that we should just use the native clients on the operating system and use the local paths in Plover.

**Closed by morinted** 2018-03-02 21:28 UTC
Labels: feature-request
