### ISSUE TITLE
output non-english characters on all operating systems

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#59] opened 2012-08-27 14:33 UTC
Plover should support outputting arbitrary characters such as ñ as long as it's possible to type them on the given OS.

**Comment by morinted** [comment] 2015-10-07 22:41
Linux could still benefit from this. The real litmus test, I find, it using emojis. OS X works and Windows is on the way. Maybe @benoit-pierre would be brave enough to try the challenge.

**Comment by morinted** [comment] 2016-02-10 21:55
Closing as duplicate of #179

**Closed by morinted** 2016-02-10 21:55 UTC
Labels: enhancement
