### ISSUE TITLE
System-specific default space

### ISSUE THREAD

**Issue by Kaoffie** [openstenoproject/plover#1353] opened 2021-06-13 08:08 UTC
I don't think there is a direct way of defining the default space in a system plugin, which is kind of a problem for systems that don't use spaces (eg. Chinese, Japanese) or other kinds of spaces (eg. Braille) 

Currently the solution is to either surround every dictionary entry with `{^^}` (which is rather unwieldy), or to have an extension plugin listening to `config_changed` and to send `{mode:set_space:}` based on the system name. It's not particularly elegant and future-proof, and the more natural way to do it would probably be to have something like `DEFAULT_SPACE = " "` in system.py that can be changed by the plugin author.

Thanks! <3

**Comment by benoit-pierre** [comment] 2021-06-13 12:26
Duplicate of #890.

**Closed by benoit-pierre** 2021-06-13 12:26 UTC
Labels: feature-request

**Comment by user202729** [comment] 2021-06-13 13:53
Almost. This one is a little more general.
