### ISSUE TITLE
Linux: Plover does not recognize non-Qwerty layout

### ISSUE THREAD

**Issue by lycheese** [openstenoproject/plover#1395] opened 2021-08-01 10:26 UTC
**Describe the bug**

When using bone as my software layout with xkb and my qmk keyboard with Plover and hitting the `STN_HL`, `STN_E` and `STN_LR` keys simultaneously Plover produces the output `ufii` instead of `hell`.

The only way I have found so far to get the expected behaviour is to specify the us layout in `/etc/X11/xorg.conf.d/00-keyboard.conf` and reboot.

**To Reproduce**

1. Specify the bone layout through xorg config files and reboot
2. Start Plover
3. Send steno keycodes via qmk and gemini pr
4. Produce garbled output

**Expected behavior**

Plover recognizes the different keyboard layout and adjusts accordingly.

**Screenshots**

Bone Layout:
![image](https://user-images.githubusercontent.com/76482001/127767096-7b193c62-248e-416e-bd0b-447463065b0e.png)

**Operating system**

 - OS: NixOS 21.05
 - Plover Version 4.0.0.dev8

**Hardware**

I am using a Kyria with qmk firmware and a dedicated Plover layer:
![image](https://user-images.githubusercontent.com/76482001/127767453-8d3627c3-8abb-4ed6-b7d3-ada96cc86856.png)
I have not made any changes to the default machine configuration apart from selecting gemini pr:
![image](https://user-images.githubusercontent.com/76482001/127767474-a698c2e5-77cf-4cde-9df7-78f6a595c873.png)

**Comment by user202729** [comment] 2021-08-01 13:14
Does

    xdotool type hell

work correctly (type the correct content `hell`)?

**Comment by lycheese** [comment] 2021-08-01 13:35
> Does
> 
> ```
> xdotool type hell
> ```
> 
> work correctly (type the correct content `hell`)?

No, it does not. But interestingly instead of Plover's `ufii` it types `ueii`.

**Comment by lycheese** [comment] 2021-08-01 20:27
It seems that the bug I encountered only happens when you have multiple keyboard layouts defined in the xorg config files. When only the bone layout is defined, the fix mentioned above (executing `setxkbmap -layout de -variant bone`) causes Plover to output the expected characters.

**Comment by user202729** [comment] 2021-08-02 07:05
Currently Plover does not support XKB properly (see https://github.com/openstenoproject/plover/pull/1164#issuecomment-812033525), fixing this issue will require "a lot of work".

There are some other unofficial "output engine plugins" such as https://github.com/user202729/plover-ibus (read the disclaimer)

**Comment by lycheese** [comment] 2021-08-02 12:30
> Currently Plover does not support XKB properly (see [#1164 (comment)](https://github.com/openstenoproject/plover/pull/1164#issuecomment-812033525)), fixing this issue will require "a lot of work".
> 
> There are some other unofficial "output engine plugins" such as https://github.com/user202729/plover-ibus (read the disclaimer)

Ah, okay. Luckily I do not need the second layout now that I have a qmk-enabled keyboard so it is no longer a problem for me. Should I close this issue or should I keep it open and make it more precise?

**Comment by benoit-pierre** [comment] 2022-06-02 10:48
Duplicate of #650.

**Closed by benoit-pierre** 2022-06-02 10:48 UTC
Labels: bug, linux
