### ISSUE TITLE
 Linux: Using non-US keyboard layouts makes special characters come up wrong.

### ISSUE THREAD

**Issue by Elktro** [openstenoproject/plover#298] opened 2015-11-11 21:14 UTC
I'm using Plover on a Linux computer (Ubuntu 15.04) and I noticed that the Plover is somehow affected by the active keyboard layout. For example, I if press PAO*EUP which mapped to "{^|^}" while I have the US keyboard selected I get the normal pipe symbol (|). If I, however, have the Finnish keyboard, which is what I usually use all the time, I get the asterisk (*).

It seems that Plover is effectively press the key left to enter-key <A011> with shift down. On the U.S. keyboard layout it creates the pipe symbol, but on the Finnish keyboard layout it is mapped to the asterisk.

This problem occurs even though I have the Finnish keyboard layout selected when I start Plover.

**Comment by benoit-pierre** [comment] 2015-11-11 21:46
It's weird that it is happening if the layout is set to Finnish *before* starting Plover. Can you try with the current Git master?

Changing layouts while Plover is running will not work, but I'm working on a fix.

**Comment by Elktro** [comment] 2015-11-12 18:05
Tested with 

 * SHA: e5c4aeb91f03f49e5e10d7f54c1dc2c2f35c3f2f

Before I ran "python launch.py", I made sure that I definitely had Finnish keyboard layout active. Still, I experienced the same problem.

**Comment by benoit-pierre** [comment] 2015-11-12 20:32
OK, can you give me the output of `setxkbmap -query` and `xmodmap -pke` with both layouts?

**Comment by Elktro** [comment] 2015-11-13 00:01
setxkbmap -query  when I have the Finnish keyboard layout selected:

rules:      evdev
model:      pc105
layout:     fi,us
variant:    ,
options:    caps:ctrl_modifier

setxkbmap -query  when I have the US keyboard layout selected:

rules:      evdev
model:      pc105
layout:     us
options:    caps:ctrl_modifier

Here are the outputs of xmodmap with the layouts:
[xmodmap_fi.txt](https://github.com/openstenoproject/plover/files/33457/xmodmap_fi.txt)
[xmodmap_us.txt](https://github.com/openstenoproject/plover/files/33458/xmodmap_us.txt)

A funny thing, that I just noticed is that some characters seemed to behave right. Such as the colon (:) or the equal sign (=). Which I have defined as

"ST-L": "=",
"TP-PBLG": "{^:}",

Could it have something to do with the fact that the pipe character needs to be typed with the "Alt Gr" or the ISO_Level3_Shift button?

Actually I have XK.load_keysym_group('xkb') in my  xkeyboardcontrol.py of my own private clone of Plover to enable me to use "Alt Gr" button.

Here's the diff of the file:

@@ -260,6 +205,8 @@ class KeyboardEmulation(object):
         """Prepare to emulate keyboard events."""
         self.display = display.Display()
         self.modifier_mapping = self.display.get_modifier_mapping()
+        # Load non-us keyboard related keysyms.
+        XK.load_keysym_group('xkb')
         # Determine the backspace keycode.
         backspace_keysym = XK.string_to_keysym('BackSpace')

**Comment by benoit-pierre** [comment] 2015-11-13 00:17
AFAIK, using `XK.load_keysym_group('xkb')` only extends the list of keysyms available with the `XK` module, that does not make them available in your keyboard layout...

As for handling "Alt Gr" combos, that's why I asked you to try with the latest Git, because I added support for it: cbedcb219e25dd21751f7fe3ccb7018d2fd1bd20

**Comment by benoit-pierre** [comment] 2015-11-13 00:46
Our handling of groups is wrong, looking into it...

**Comment by benoit-pierre** [comment] 2015-11-13 03:34
So, bad news, bad news...

Without proper support for the XKB extension, there is not way to correctly handle groups... Even worse, the current support for "Alt Gr" combos will not work if more than 1 group is used:

- we can't set higher modifiers bits when sending a key press/release event with `XSendEvent` to latch the correct group
- and even if we could, the keymap information reported by Xlib (without XKB) is not valid when more than 1 group is used (same as with the output of `xmodmap -pk` utility really)

**Comment by morinted** [comment] 2016-02-10 21:05
For this issue, if we can at least get to a point where our limitations are defined and we are better off than the current situation, then we can at least claim an improvement. I'd like to have this in for Plover next.

**Comment by Elktro** [comment] 2016-02-11 14:34
The way I have gotten the pipe symbol working is by defining a dictionary entry:

`"PAO*EUP": "{#ISO_Level3_Shift(less)}"
`

Where the ISO_Level3_shift key as a meta key is enabled by the `XK.load_keysym_group('xkb')`  in the xkeyboardcontrol.py.

This is, of course, not even close to the solution and these kind of entries make the dictionaries keyboard layout specific but it was the only way I was able to get the pipe symbol working with the Finnish keyboard layout.

**Comment by jeremy-w** [comment] 2016-04-26 02:02
@benoit-pierre It reads like you have a good understanding of this issue. Is there a solution possible, even if it's one we can't readily implement just now?

**Comment by benoit-pierre** [comment] 2016-04-26 13:21
We need XKB support in `python-xlib`.

**Comment by benoit-pierre** [comment] 2017-07-18 07:51
Duplicate of #650.

**Closed by benoit-pierre** 2017-07-18 07:51 UTC
Labels: bug, confirmed, medium-priority
