### ISSUE TITLE
Releasing a key with different modifiers causes the key to "stick"

### ISSUE THREAD

**Issue by KeyboardFire** [openstenoproject/plover#597] opened 2016-09-23 19:15 UTC
Steps to reproduce this bug:

1. Press any key that is used for steno (ex. Q on qwerty, which maps to steno S).
2. Press any modifier key (shift, ctrl, alt, etc.).
3. Release the first key that was pressed.
4. Release the modifer key.

Since the key was released with the modifier held down, Plover doesn't see it as the same key and thinks the key was never released, continuing to wait for the chord to be completed.

This isn't an issue if you're only typing in steno since modifier keys aren't used anyway, but I frequently switch between steno and qwerty. Rapid typing in qwerty causes the situation described to occur fairly commonly (usually when failing to release the last letter or two of a previous word while typing a subsequent capitalized word), and then trying to chord the `{PLOVER:TOGGLE}` command doesn't work.

Reproduced in 3.0.0+253.g244f590 (the current latest commit), installed via AUR.

**Comment by benoit-pierre** [comment] 2016-10-01 16:56
OK, so the issue is fixed on Linux, we need the corresponding changes for OS X and Windows.

- [X] Linux
- [ ] OS X
- [ ] Windows

**Closed** 2016-10-01 17:29 UTC

**Comment by morinted** [comment] 2016-10-01 17:31
Thanks @KeyboardFire for pointing this out. It must have been a long-standing bug!
