### ISSUE TITLE
Plover crashing upon switching between different systems

### ISSUE THREAD

**Issue by nikyq** [openstenoproject/plover#1448] opened 2021-12-11 12:35 UTC
Hi, I'm using Plover 4.0.0 dev 10+115 version on Manjaro Linux with English and Korean systems. The Korean system can be found here: https://github.com/nsmarkop/plover_korean (It doesn't seem like it is being actively maintained since 2019)

After I switch __from the Korean system to the English system__ (while using Plover without turning the program off and on),  whenever I try to stroke something I get the following error.

 ```
 2021-12-11 21:22:54,820 [Dummy-1] ERROR: engine on_stroked failed
Traceback (most recent call last):
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 147, in run
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 383, in _on_stroked
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 206, in translate
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 303, in translate_stroke
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 353, in _find_translation_helper
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 391, in _lookup_with_prefix
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 360, in lookup
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 360, in <genexpr>
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/steno.py", line 86, in rtfcre
ValueError
2021-12-11 21:22:54,826 [Dummy-1] ERROR: engine on_stroked failed
Traceback (most recent call last):
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 147, in run
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 383, in _on_stroked
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 206, in translate
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 303, in translate_stroke
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 353, in _find_translation_helper
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 391, in _lookup_with_prefix
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 360, in lookup
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/translation.py", line 360, in <genexpr>
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/steno.py", line 86, in rtfcre
ValueError
```

 For reference, I tried disabling every dictionary for each system but the issue persisted. I have no idea what is causing this problem.

**Comment by user202729** [comment] 2021-12-11 12:47
Looks like a new issue with the plover_stroke C extension or something. The helper state is global, so it's possible that something  (plover-dict-commands?) may construct a new stroke instance in the old system.

**Comment by benoit-pierre** [comment] 2021-12-11 12:56
Might be a duplicate of #893, how do you switch?

**Comment by nikyq** [comment] 2021-12-11 13:41
> Might be a duplicate of #893, how do you switch?

 With the Configure menu. I wasn't keeping the tape window open either.

**Closed** 2022-02-06 17:00 UTC
Labels: bug
