### ISSUE TITLE
Special support for Chrome address bar

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1141] opened 2020-08-29 17:39 UTC
## Summary

When using Plover in the Chrome address bar, an issue comes up with some words that involve Plover sending the backspace key. For example, the domain YouTube.com comes out as yYouTube.

More info from Ted here:
https://teds.space/posts/type-urls-in-steno-disable-inline

## Reproducing

Use the following strokes:
 S             P       
            U          
  T     AO  U   B 

Expected output:
YouTube

Actual output:
yYouTube

## Plover Version

Plover 4.0.0.dev8+66.g685bd33

## System

macOS 10.15.5

**Comment by parnikkapore** [comment] 2020-09-09 09:51
Irreproducible here. Linux Mint 20.0, Plover 4.0.0.dev8+66.g685bd33, Chrome 85.0.4183.102

**Comment by richyliu** [comment] 2020-11-22 06:17
I have encountered this problem on several browsers as well. One possible solution would to press a space before pressing backspace when correcting a word.

For example, `U/TAOUB` would produce "you" => "you " (notice the space) => "" => "YouTube".

This seems to fix the "yYoutube" problem, at least on Chrome and Safari on MacOS.

**Comment by gdwaynewarner** [comment] 2021-04-28 21:53
Might be a good idea to just make an outline for YouTube (mine is KWRAO*-UB).

Follow that up with an outline for ".com," or use Phoenix Theory's famous R-R stroke --

KWRAO*-UB /R-R

-- to give you youtube.com.

You could also assign one of those two outlines to give you "youtube" by removing the asterisk.

.... and you can also turn off that AutoCorrect feature, if possible ... but the outline idea would probably be less intrusive.

**Comment by richyliu** [comment] 2021-04-29 00:25
Could you tell me more about Phoenix's R-R stroke? That sounds quite interesting.

**Comment by gdwaynewarner** [comment] 2021-04-29 06:38
There's not really much more to tell!

It was originally used to differentiate between words like "to" (TAO) and "too" (TAO*), for those times you forget or assume the one "to" was correct but it wasn't.

I don't use it very much, but when I have the option of making an outline for something like "YouTube" and find that I sometimes need "youtube.com," I can use the same stroke, and follow it with the R-R stroke, and have it tran as the address.

Probably as clear as mud, but it does come in handy.

**Comment by antistic** [comment] 2021-12-14 17:28
Chrome does not let you turn off autocomplete like Firefox does. There's an issue (opened in 2011) about it here: https://bugs.chromium.org/p/chromium/issues/detail?id=91378, but it looks like it's not going to get solved on the chrome end any time soon.

**Comment by benoit-pierre** [comment] 2022-02-27 16:19
Closing, as there's really nothing actionable on Plover' side.

Note: as a possible workaround, would switching the output mode to "space after" when in the Chrome address bar fix the issue?

**Closed by benoit-pierre** 2022-02-27 16:19 UTC

**Comment by user202729** [comment] 2022-03-01 08:44
There are experimental ibus output plugin/patches https://github.com/openstenoproject/plover/discussions/1390 , but it has other issues.
