### ISSUE TITLE
speed up rtf loading time

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#129] opened 2013-10-22 20:43 UTC
RTF loading may be too slow.

Also, it's been reported that RTF loading time is longer on startup than when later added.

**Comment by morinted** [comment] 2015-10-07 22:50
Is this because we have to parse it on start up, unlike JSON which we parse on stroke?

**Comment by jeremy-w** [comment] 2016-02-16 17:00
Anyone have a sample "this is way too slow" RTF dictionary to reproduce this against?

**Comment by user202729** [comment] 2021-04-05 15:06
There's https://github.com/sammdot/plover-better-rtf (which claims to be faster)

**Comment by benoit-pierre** [comment] 2022-02-27 14:52
Closing, #1365 + #1362 really sped things up.

**Closed by benoit-pierre** 2022-02-27 14:52 UTC
Labels: low-priority, feature-request, needs-testing, rtf
