### ISSUE TITLE
windows: plover can't type in virtualbox guest

### ISSUE THREAD

**Issue by rbrewer123** [openstenoproject/plover#656] opened 2016-12-16 16:55 UTC
Classification: Bug 

Reproducibility: Always

## Summary

On Windows 7, running plover on the host OS does not allow entering keys to guest OSs in virtualbox.

## Steps to Reproduce

1. start plover 
2. start virtualbox
3. start a guestin virtualbox (I used ubuntu 14.04)
4. try to use plovereto type in the guest

## Expected Results

Plover should enter keys normally in the guest.

## Actual Results

Plover shows the strokes in the suggestion window, but the strokes are not seen in the guest.

## Version

Plover 3.1.0 using TXbolt protocol
windows 7 sp1 host
Virtualbox 5.1.8
Ubuntu 14.04 guest

Installed via: download from github

## Notes

Looked for virtualbox settings that might be related but found none.

Tried plover (using nkro protocol) on an Ubuntu 14.04 host with virtualbox and a Windows 7 guest and it did enter text on the guest.  So the problem seems to be specific to Plover hosted on Windows.

## Configuration

Plover 3.1.0 using TXbolt protocol
windows 7 sp1 host
Virtualbox 5.1.8
Ubuntu 14.04 guest

**Comment by morinted** [comment] 2016-12-16 17:05
Could you try out your configuration on 2.5.8 to see if the old way of sending keyshortcuts works for VBox?

**Comment by rbrewer123** [comment] 2016-12-16 19:58
I tried plover 2.5.8 and wasn't able to get TXbolt talking to my steno machine, so I used nkro protocol.  I saw plover put correctly-translated steno in my host windows, but inside the ubuntu 14.04 guest I only saw normal keypresses, as if I wasn't running plover at all.

**Comment by morinted** [comment] 2017-02-09 14:50
It might be a limitation in the way VirtualBox handles keyboards on Windows. On Mac, VirtualBox works fine with Plover. Have you tried a different VM software to see if we can offer a suggestion for anyone facing this issue in the future? (E.g. VMWare)

**Comment by tschulte** [comment] 2017-02-14 21:35
As a workaround: there exist tools to duplicate com ports (commercial, I don't remember which one, but I once tried one of them). If you normally only have e.g. COM1, that tool would create COM2. Then you would have to start Plover on Windows connected to COM1. Virtualbox would be configured to use COM2, and within your guest, you need to start a second instance of Plover. When using a N-Key keyboard instead, you don't even need the com port redirector (which are proprietary commercial tools).

Or if you only need plover within the guest, and not on the host, you can give virtualbox access to the com port and only start plover in the guest.

**Comment by tschulte** [comment] 2017-02-24 08:51
I can confirm, that this issue does not exist with VMWare. I had the same issue while using VirtualBox with Linux guest on Windows host. After switching to VMWare, it works.

**Comment by morinted** [comment] 2017-02-24 15:29
Thanks for the input (no pun intended)…for now I'll close this and say that Plover doesn't seem to work over VirtualBox on Windows, and that users may consider switching to VMWare or forwarding their serial ports to run Plover on the guest, if necessary. Thanks Tobias!

**Closed by morinted** 2017-02-24 15:29 UTC
Labels: bug, low-priority

**Comment by tschulte** [comment] 2018-11-20 10:00
With VMWare Workstation Player 15.0.1 build-10737736/Plover 4.0.0.dev8+66.g685bd33 it does not work anymore. I don't know, if VMWare changed something or if Plover changed.

Now the behavior is exactly as in Virtualbox: "Plover shows the strokes in the suggestion window, but the strokes are not seen in the guest."
