### ISSUE TITLE
Some Unicode characters aren't emitted on Linux when switching ibus input methods

### ISSUE THREAD

**Issue by 42triangles** [openstenoproject/plover#1296] opened 2021-04-24 13:55 UTC
**Describe the bug**

Some Unicode  characters aren't emitted after changing ibus input methods back and forth between English (in the British layout) and Japanese (anthy). This is an issue for multiple characters in the hiragana block, but not all of them, and I can't make out any pattern.

Testing with `xev` I just see:

```
KeyPress event, serial 89, synthetic NO, window 0x5c00001,
    root 0x1ed, subw 0x0, time 256465103, (-915,607), root:(3021,627),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 89, synthetic NO, window 0x5c00001,
    root 0x1ed, subw 0x0, time 256465103, (-915,607), root:(3021,627),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

While it should look like this:

```
KeyPress event, serial 45, synthetic NO, window 0x5c00001,
    root 0x1ed, subw 0x0, time 256419523, (-623,553), root:(3313,573),
    state 0x0, keycode 8 (keysym 0x100304b, U304B), same_screen YES,
    XLookupString gives 3 bytes: (e3 81 8b) "か"
    XmbLookupString gives 3 bytes: (e3 81 8b) "か"
    XFilterEvent returns: False

KeyRelease event, serial 45, synthetic NO, window 0x5c00001,
    root 0x1ed, subw 0x0, time 256419524, (-623,553), root:(3313,573),
    state 0x0, keycode 8 (keysym 0x100304b, U304B), same_screen YES,
    XLookupString gives 3 bytes: (e3 81 8b) "か"
    XFilterEvent returns: False
```

**To Reproduce**

* Start Plover, have some translation to か somewhere, and some translation that switches input methods
* Using that translation for か works
* Switch input methods using Plover
* Write anything
* Switch back
* Using that か translation don't work anymore
* Restarting Plover fixes the issue

**Expected behavior**

The Unicode character would be emitted correctly.

**Operating system**

 - OS:  Arch Linux, up to date for the 2021-04-24
 - Plover Version: weekly

**Comment by user202729** [comment] 2021-04-24 15:43
Duplicate of #967

**Closed by user202729** 2021-04-24 15:43 UTC
Labels: bug, linux
